### ISSUE TITLE
revived npc is not same-ticked with npc

### ISSUE THREAD

**Issue by Supalosa** [OldSchoolSDK/InfernoTrainer#89]
currently, when an NPC is revived, the attack timing is incorrect - it seems to resume its original attack cycle.

In the actual game, the first attack should be 8 ticks after it's revived (i.e. same-ticked with the thing that revived it).

**Comment by TeslaOwner** [comment]
👍 easy fix

**Comment by TeslaOwner** [comment]
fixed in #94
